class Gn < Formula
  desc "GN is a meta-build system that generates build files for Ninja."
  homepage "https://gn.googlesource.com/gn"
  url "https://gn.googlesource.com/gn/+archive/refs/heads/main.tar.gz"
  sha256 "2e245ce5cbc275f6924ce09d8194702691fc91d88e8e94c4e403cf96c81db887"
  license "BSD-3-Clause"
  version '2025.07.02'

  depends_on "python@3.10" => :build
  depends_on "ninja" => :build

  def install
    ENV.deparallelize  # if your formula fails when building in parallel
    system "python3", "build/gen.py", "--no-last-commit-position"

    system "echo // Generated by build/gen.py. > out/last_commit_position.h"
    system "echo '#ifndef OUT_LAST_COMMIT_POSITION_H_' >> out/last_commit_position.h"
    system "echo '#define OUT_LAST_COMMIT_POSITION_H_' >> out/last_commit_position.h"
    system "echo '#define LAST_COMMIT_POSITION_NUM 2056' >> out/last_commit_position.h"
    system "echo '#define LAST_COMMIT_POSITION \"2056 (0bcd37bd2b83)\"' >> out/last_commit_position.h"
    system "echo '#endif  // OUT_LAST_COMMIT_POSITION_H_' >> out/last_commit_position.h"

    system "ninja", "-C", "out"
    system "mkdir", "-p", "#{prefix}/bin"
    system "cp", "out/gn", "#{prefix}/bin/"
    system "out/gn_unittests"
  end
end
